export const OPEN_DRAWER = "OPEN_DRAWER";
export const HIDE_DRAWER = "HIDE_DRAWER";
export const OPEN_PROM_EDIT_PROJECT = "OPEN_PROM_EDIT_PROJECT";
export const OPENT_FORM_CREATE_TASK = "OPENT_FORM_CREATE_TASK";
