export const GET_ALL_PROJECT ="GET_ALL_PROJECT"
export const EDIT_PROJECT ="EDIT_PROJECT"
export const ASSIGN_USER_PROJECT = "ASSIGN_USER_PROJECT";
export const PROJECT_DETAIL = "PROJECT_DETAIL";
export const GET_TASK_DETAIL = "GET_TASK_DETAIL"




export const  CHANGE_ASSIGNESS="CHANGE_ASSIGNESS"
export const  CHANGE_TASK_MODAL="CHANGE_TASK_MODAL"
export const  REMOVE_USER_ASSIGN="REMOVE_USER_ASSIGN"