export const LOGIN_SAGA = "LOGIN_SAGA";
export const REGISTER_SAGA = "REGISTER_SAGA";
export const GET_ALL_USER_PROJECT_SAGA = "GET_ALL_USER_PROJECT_SAGA";
export const SEARCH_USER_SAGA = "SEARCH_USER_SAGA";
